name: flutter_alzhecare_cnn
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0

environment:
  sdk: ^3.11.4

dependencies:
  equatable: ^2.0.8
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.9
  flutter_bloc: ^9.1.1
  flutter_native_splash: ^2.4.7
  http: ^1.6.0
  image_picker: ^1.2.1
  intl: ^0.20.2
  provider: ^6.1.5
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  

flutter:
  uses-material-design: true
  assets:
  - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  adaptive_icon_background: "#2563EB"
  adaptive_icon_foreground: "assets/images/icon.png"


flutter_native_splash:
  color: "#F4F7FB"
  color_dark: "#10263D"
  image: assets/images/icon_splash.png
  image_dark: assets/images/icon_splash.png

  android_12:
    color: "#F4F7FB"
    color_dark: "#10263D"
    image: assets/images/icon_splash.png
    image_dark: assets/images/icon_splash.png

  web: true
  android: true
  ios: true
  fullscreen: false